// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SonaraDbContext))]
    [Migration("20260814035117_AddCatalogSearchAndLibraryIndexes")]
    partial class AddCatalogSearchAndLibraryIndexes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Music.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Albums_Title");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-111111111111"),
                            ArtistId = new Guid("66666666-6666-6666-6666-111111111111"),
                            CoverUrl = "https://sonarastorage.blob.core.windows.net/images/albums/album_1.jpg",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReleaseDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Neon Nights",
                            Type = "LP"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-222222222222"),
                            ArtistId = new Guid("66666666-6666-6666-6666-222222222222"),
                            CoverUrl = "https://sonarastorage.blob.core.windows.net/images/albums/album_2.jpg",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReleaseDate = new DateTime(2023, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Deep Ocean",
                            Type = "EP"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-333333333333"),
                            ArtistId = new Guid("66666666-6666-6666-6666-333333333333"),
                            CoverUrl = "https://sonarastorage.blob.core.windows.net/images/albums/album_3.jpg",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReleaseDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Piano Echoes",
                            Type = "LP"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-444444444444"),
                            ArtistId = new Guid("66666666-6666-6666-6666-444444444444"),
                            CoverUrl = "https://sonarastorage.blob.core.windows.net/images/albums/album_4.jpg",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReleaseDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "System Crash",
                            Type = "Single"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-555555555555"),
                            ArtistId = new Guid("66666666-6666-6666-6666-555555555555"),
                            CoverUrl = "https://sonarastorage.blob.core.windows.net/images/albums/album_5.jpg",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReleaseDate = new DateTime(2024, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sunset Chill",
                            Type = "EP"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Music.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-111111111111"),
                            Name = "Synthwave"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-222222222222"),
                            Name = "Ambient"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-333333333333"),
                            Name = "Classical"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-444444444444"),
                            Name = "Cyberpunk"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-555555555555"),
                            Name = "Acoustic"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Music.ListeningHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DurationListenedMs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ListenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("UserId", "ListenedAt")
                        .HasDatabaseName("IX_ListeningHistories_UserId_ListenedAt");

                    b.ToTable("ListeningHistories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-111111111111"),
                            DurationListenedMs = 210000,
                            ListenedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TrackId = new Guid("99999999-9999-9999-9999-111111111111"),
                            UserId = new Guid("33333333-3333-3333-3333-111111111111")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-222222222222"),
                            DurationListenedMs = 120000,
                            ListenedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TrackId = new Guid("99999999-9999-9999-9999-222222222222"),
                            UserId = new Guid("33333333-3333-3333-3333-222222222222")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-333333333333"),
                            DurationListenedMs = 185000,
                            ListenedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TrackId = new Guid("99999999-9999-9999-9999-333333333333"),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-444444444444"),
                            DurationListenedMs = 90000,
                            ListenedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TrackId = new Guid("99999999-9999-9999-9999-444444444444"),
                            UserId = new Guid("33333333-3333-3333-3333-444444444444")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-555555555555"),
                            DurationListenedMs = 160000,
                            ListenedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TrackId = new Guid("99999999-9999-9999-9999-555555555555"),
                            UserId = new Guid("33333333-3333-3333-3333-555555555555")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Music.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<long>("PlaysCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Tracks_CreatedAt");

                    b.HasIndex("PlaysCount")
                        .HasDatabaseName("IX_Tracks_PlaysCount");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Tracks_Title");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-111111111111"),
                            AlbumId = new Guid("77777777-7777-7777-7777-111111111111"),
                            ArtistId = new Guid("66666666-6666-6666-6666-111111111111"),
                            AudioUrl = "https://sonarastorage.blob.core.windows.net/audio/tracks/tracks_1.mp3",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMs = 210000,
                            PlaysCount = 12500L,
                            Title = "Midnight City Drive"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-222222222222"),
                            AlbumId = new Guid("77777777-7777-7777-7777-222222222222"),
                            ArtistId = new Guid("66666666-6666-6666-6666-222222222222"),
                            AudioUrl = "https://sonarastorage.blob.core.windows.net/audio/tracks/tracks_2.mp3",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMs = 340000,
                            PlaysCount = 8400L,
                            Title = "Abyssal Silence"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-333333333333"),
                            AlbumId = new Guid("77777777-7777-7777-7777-333333333333"),
                            ArtistId = new Guid("66666666-6666-6666-6666-333333333333"),
                            AudioUrl = "https://sonarastorage.blob.core.windows.net/audio/tracks/tracks_3.mp3",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMs = 185000,
                            PlaysCount = 3200L,
                            Title = "Moonlight Sonata Var."
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-444444444444"),
                            AlbumId = new Guid("77777777-7777-7777-7777-444444444444"),
                            ArtistId = new Guid("66666666-6666-6666-6666-444444444444"),
                            AudioUrl = "https://sonarastorage.blob.core.windows.net/audio/tracks/tracks_4.mp3",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMs = 195000,
                            PlaysCount = 45000L,
                            Title = "Overdrive"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-555555555555"),
                            AlbumId = new Guid("77777777-7777-7777-7777-555555555555"),
                            ArtistId = new Guid("66666666-6666-6666-6666-555555555555"),
                            AudioUrl = "https://sonarastorage.blob.core.windows.net/audio/tracks/tracks_5.mp3",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMs = 160000,
                            PlaysCount = 6100L,
                            Title = "Warm Breeze"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Music.TrackGenre", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid");

                    b.HasKey("TrackId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("TrackGenres");

                    b.HasData(
                        new
                        {
                            TrackId = new Guid("99999999-9999-9999-9999-111111111111"),
                            GenreId = new Guid("88888888-8888-8888-8888-111111111111")
                        },
                        new
                        {
                            TrackId = new Guid("99999999-9999-9999-9999-222222222222"),
                            GenreId = new Guid("88888888-8888-8888-8888-222222222222")
                        },
                        new
                        {
                            TrackId = new Guid("99999999-9999-9999-9999-333333333333"),
                            GenreId = new Guid("88888888-8888-8888-8888-333333333333")
                        },
                        new
                        {
                            TrackId = new Guid("99999999-9999-9999-9999-444444444444"),
                            GenreId = new Guid("88888888-8888-8888-8888-444444444444")
                        },
                        new
                        {
                            TrackId = new Guid("99999999-9999-9999-9999-555555555555"),
                            GenreId = new Guid("88888888-8888-8888-8888-555555555555")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Playlists.LikedTrack", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "TrackId");

                    b.HasIndex("TrackId");

                    b.HasIndex("UserId", "LikedAt")
                        .HasDatabaseName("IX_LikedTracks_UserId_LikedAt");

                    b.ToTable("LikedTracks");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-111111111111"),
                            TrackId = new Guid("99999999-9999-9999-9999-111111111111"),
                            LikedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-222222222222"),
                            TrackId = new Guid("99999999-9999-9999-9999-222222222222"),
                            LikedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TrackId = new Guid("99999999-9999-9999-9999-333333333333"),
                            LikedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-444444444444"),
                            TrackId = new Guid("99999999-9999-9999-9999-444444444444"),
                            LikedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-555555555555"),
                            TrackId = new Guid("99999999-9999-9999-9999-555555555555"),
                            LikedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Playlists.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Playlists_Name");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_Playlists_UserId_CreatedAt");

                    b.ToTable("Playlists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-111111111111"),
                            CoverUrl = "https://sonarastorage.blob.core.windows.net/images/playlists/playlists_1.jpg",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Best tracks for late-night coding.",
                            IsPrivate = false,
                            Name = "Night Vibes",
                            UserId = new Guid("33333333-3333-3333-3333-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-222222222222"),
                            CoverUrl = "https://sonarastorage.blob.core.windows.net/images/playlists/playlists_2.jpg",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ambient background soundscapes.",
                            IsPrivate = false,
                            Name = "Focus & Flow",
                            UserId = new Guid("33333333-3333-3333-3333-222222222222")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-333333333333"),
                            CoverUrl = "https://sonarastorage.blob.core.windows.net/images/playlists/playlists_3.jpg",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Peaceful piano compositions.",
                            IsPrivate = true,
                            Name = "Classical Chill",
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-444444444444"),
                            CoverUrl = "https://sonarastorage.blob.core.windows.net/images/playlists/playlists_4.jpg",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fast & aggressive synth sounds.",
                            IsPrivate = false,
                            Name = "Cyberpunk Mix",
                            UserId = new Guid("33333333-3333-3333-3333-444444444444")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-555555555555"),
                            CoverUrl = "https://sonarastorage.blob.core.windows.net/images/playlists/playlists_5.jpg",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft guitar tracks.",
                            IsPrivate = false,
                            Name = "Acoustic Favorites",
                            UserId = new Guid("33333333-3333-3333-3333-555555555555")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Playlists.PlaylistTrack", b =>
                {
                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PlaylistId", "TrackId");

                    b.HasIndex("TrackId");

                    b.HasIndex("PlaylistId", "AddedAt")
                        .HasDatabaseName("IX_PlaylistTracks_PlaylistId_AddedAt");

                    b.ToTable("PlaylistTracks");

                    b.HasData(
                        new
                        {
                            PlaylistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-111111111111"),
                            TrackId = new Guid("99999999-9999-9999-9999-111111111111"),
                            AddedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PlaylistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-222222222222"),
                            TrackId = new Guid("99999999-9999-9999-9999-222222222222"),
                            AddedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PlaylistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-333333333333"),
                            TrackId = new Guid("99999999-9999-9999-9999-333333333333"),
                            AddedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PlaylistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-444444444444"),
                            TrackId = new Guid("99999999-9999-9999-9999-444444444444"),
                            AddedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PlaylistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-555555555555"),
                            TrackId = new Guid("99999999-9999-9999-9999-555555555555"),
                            AddedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Podcasts.Podcast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Podcasts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-111111111111"),
                            AuthorId = new Guid("33333333-3333-3333-3333-555555555555"),
                            CoverUrl = "https://sonarastorage.blob.core.windows.net/images/podcasts/podcasts_1.jpg",
                            Description = "Latest insights into software engineering.",
                            Title = "Tech Talk Daily"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-222222222222"),
                            AuthorId = new Guid("33333333-3333-3333-3333-111111111111"),
                            CoverUrl = "https://sonarastorage.blob.core.windows.net/images/podcasts/podcasts_2.jpg",
                            Description = "How to mix and master your tracks.",
                            Title = "Music Production 101"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-333333333333"),
                            AuthorId = new Guid("33333333-3333-3333-3333-222222222222"),
                            CoverUrl = "https://sonarastorage.blob.core.windows.net/images/podcasts/podcasts_3.jpg",
                            Description = "Discussions on sound design and field recording.",
                            Title = "Ambient Life"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-444444444444"),
                            AuthorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CoverUrl = "https://sonarastorage.blob.core.windows.net/images/podcasts/podcasts_4.jpg",
                            Description = "Deep dives into legendary composers.",
                            Title = "Classical History"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-555555555555"),
                            AuthorId = new Guid("33333333-3333-3333-3333-444444444444"),
                            CoverUrl = "https://sonarastorage.blob.core.windows.net/images/podcasts/podcasts_5.jpg",
                            Description = "Sci-fi movies, music, and gaming.",
                            Title = "Cyber Culture"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Podcasts.PodcastEpisode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("PodcastId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PodcastId");

                    b.ToTable("PodcastEpisodes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-111111111111"),
                            AudioUrl = "https://sonarastorage.blob.core.windows.net/audio/podcasts/podcasts_1.mp3",
                            DurationMs = 1800000,
                            PodcastId = new Guid("cccccccc-cccc-cccc-cccc-111111111111"),
                            ReleaseDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Ep 1: C# and .NET Features"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-222222222222"),
                            AudioUrl = "https://sonarastorage.blob.core.windows.net/audio/podcasts/podcasts_2.mp3",
                            DurationMs = 2400000,
                            PodcastId = new Guid("cccccccc-cccc-cccc-cccc-222222222222"),
                            ReleaseDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Ep 1: Choosing Your First DAW"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-333333333333"),
                            AudioUrl = "https://sonarastorage.blob.core.windows.net/audio/podcasts/podcasts_3.mp3",
                            DurationMs = 1500000,
                            PodcastId = new Guid("cccccccc-cccc-cccc-cccc-333333333333"),
                            ReleaseDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Ep 1: The Magic of Reverb"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-444444444444"),
                            AudioUrl = "https://sonarastorage.blob.core.windows.net/audio/podcasts/podcasts_4.mp3",
                            DurationMs = 2100000,
                            PodcastId = new Guid("cccccccc-cccc-cccc-cccc-444444444444"),
                            ReleaseDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Ep 1: Chopin’s Nocturnes"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-555555555555"),
                            AudioUrl = "https://sonarastorage.blob.core.windows.net/audio/podcasts/podcasts_5.mp3",
                            DurationMs = 2700000,
                            PodcastId = new Guid("cccccccc-cccc-cccc-cccc-555555555555"),
                            ReleaseDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Ep 1: Retrofuturism in Games"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Social.Follower", b =>
                {
                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FollowedId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FollowerId", "FollowedId");

                    b.HasIndex("FollowedId");

                    b.ToTable("Followers");

                    b.HasData(
                        new
                        {
                            FollowerId = new Guid("33333333-3333-3333-3333-222222222222"),
                            FollowedId = new Guid("33333333-3333-3333-3333-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FollowerId = new Guid("33333333-3333-3333-3333-333333333333"),
                            FollowedId = new Guid("33333333-3333-3333-3333-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FollowerId = new Guid("33333333-3333-3333-3333-444444444444"),
                            FollowedId = new Guid("33333333-3333-3333-3333-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FollowerId = new Guid("33333333-3333-3333-3333-555555555555"),
                            FollowedId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FollowerId = new Guid("33333333-3333-3333-3333-111111111111"),
                            FollowedId = new Guid("33333333-3333-3333-3333-555555555555"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Social.ListeningRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentTrackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTrackId");

                    b.HasIndex("HostId");

                    b.ToTable("ListeningRooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentTrackId = new Guid("99999999-9999-9999-9999-111111111111"),
                            HostId = new Guid("33333333-3333-3333-3333-111111111111"),
                            IsActive = true,
                            Name = "Synth Party"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentTrackId = new Guid("99999999-9999-9999-9999-222222222222"),
                            HostId = new Guid("33333333-3333-3333-3333-222222222222"),
                            IsActive = true,
                            Name = "Chill Lounge"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentTrackId = new Guid("99999999-9999-9999-9999-333333333333"),
                            HostId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = false,
                            Name = "Piano Study Group"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-444444444444"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentTrackId = new Guid("99999999-9999-9999-9999-444444444444"),
                            HostId = new Guid("33333333-3333-3333-3333-444444444444"),
                            IsActive = true,
                            Name = "Cyber Wave"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-555555555555"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentTrackId = new Guid("99999999-9999-9999-9999-555555555555"),
                            HostId = new Guid("33333333-3333-3333-3333-555555555555"),
                            IsActive = false,
                            Name = "Acoustic Hour"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Social.RoomMember", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoomId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("RoomMembers");

                    b.HasData(
                        new
                        {
                            RoomId = new Guid("eeeeeeee-eeee-eeee-eeee-111111111111"),
                            UserId = new Guid("33333333-3333-3333-3333-222222222222"),
                            JoinedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoomId = new Guid("eeeeeeee-eeee-eeee-eeee-222222222222"),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            JoinedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoomId = new Guid("eeeeeeee-eeee-eeee-eeee-333333333333"),
                            UserId = new Guid("33333333-3333-3333-3333-444444444444"),
                            JoinedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoomId = new Guid("eeeeeeee-eeee-eeee-eeee-444444444444"),
                            UserId = new Guid("33333333-3333-3333-3333-555555555555"),
                            JoinedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoomId = new Guid("eeeeeeee-eeee-eeee-eeee-555555555555"),
                            UserId = new Guid("33333333-3333-3333-3333-111111111111"),
                            JoinedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Users.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Artists_Name");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-111111111111"),
                            AvatarUrl = "https://sonarastorage.blob.core.windows.net/images/avatars/avatar_1.jpg",
                            Bio = "Indie synthwave producer from Kyiv.",
                            Name = "The Midnight Wave",
                            UserId = new Guid("33333333-3333-3333-3333-111111111111"),
                            Verified = true
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-222222222222"),
                            AvatarUrl = "https://sonarastorage.blob.core.windows.net/images/avatars/avatar_2.jpg",
                            Bio = "Electronic & Ambient music creator.",
                            Name = "Alex Sound",
                            UserId = new Guid("33333333-3333-3333-3333-222222222222"),
                            Verified = true
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-333333333333"),
                            AvatarUrl = "https://sonarastorage.blob.core.windows.net/images/avatars/avatar_3.jpg",
                            Bio = "Classical pianist making modern neo-classical.",
                            Name = "Maria Keys",
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Verified = true
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-444444444444"),
                            AvatarUrl = "https://sonarastorage.blob.core.windows.net/images/avatars/avatar_4.jpg",
                            Bio = "Industrial Cyberpunk soundscapes.",
                            Name = "CyberPulse",
                            UserId = new Guid("33333333-3333-3333-3333-444444444444"),
                            Verified = false
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-555555555555"),
                            AvatarUrl = "https://sonarastorage.blob.core.windows.net/images/avatars/avatar_5.jpg",
                            Bio = "Chill acoustic guitar vibes.",
                            Name = "Acoustic Dreams",
                            UserId = new Guid("33333333-3333-3333-3333-555555555555"),
                            Verified = false
                        });
                });

            modelBuilder.Entity("Domain.Entities.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Token = "sample_refresh_token_1",
                            UserId = new Guid("33333333-3333-3333-3333-111111111111")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Users.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "User"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-222222222222"),
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Users.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceName = "Windows PC - Chrome",
                            IpAddress = "192.168.1.10",
                            LastActiveAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("33333333-3333-3333-3333-111111111111")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Users.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-111111111111"),
                            Features = "Ads included, Audio standard quality, Shuffle only",
                            Name = "Free",
                            Price = 0.00m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Features = "No ads, High quality audio, Offline downloads",
                            Name = "Premium",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-333333333333"),
                            Features = "Up to 6 accounts, Explicit filter, Shared mix",
                            Name = "Family",
                            Price = 7.99m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-111111111111"),
                            AvatarUrl = "https://sonarastorage.blob.core.windows.net/images/avatars/avatar_1.jpg",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john@example.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEJrO2K4+14xWd2zC2E9vE9xN5/6+7y8z9A0B1C2D3E4F5G6H7I8J9K0L1M2N3O4P==",
                            RoleId = new Guid("11111111-1111-1111-1111-222222222222"),
                            SubscriptionId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Username = "john_doe"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-222222222222"),
                            AvatarUrl = "https://sonarastorage.blob.core.windows.net/images/avatars/avatar_2.jpg",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alex@example.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEJrO2K4+14xWd2zC2E9vE9xN5/6+7y8z9A0B1C2D3E4F5G6H7I8J9K0L1M2N3O4P==",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubscriptionId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Username = "alex_sound"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AvatarUrl = "https://sonarastorage.blob.core.windows.net/images/avatars/avatar_3.jpg",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria@example.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEJrO2K4+14xWd2zC2E9vE9xN5/6+7y8z9A0B1C2D3E4F5G6H7I8J9K0L1M2N3O4P==",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubscriptionId = new Guid("22222222-2222-2222-2222-333333333333"),
                            Username = "maria_keys"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-444444444444"),
                            AvatarUrl = "https://sonarastorage.blob.core.windows.net/images/avatars/avatar_4.jpg",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "listener@example.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEJrO2K4+14xWd2zC2E9vE9xN5/6+7y8z9A0B1C2D3E4F5G6H7I8J9K0L1M2N3O4P==",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubscriptionId = new Guid("22222222-2222-2222-2222-111111111111"),
                            Username = "listener99"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-555555555555"),
                            AvatarUrl = "https://sonarastorage.blob.core.windows.net/images/avatars/avatar_5.jpg",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "podcaster@example.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEJrO2K4+14xWd2zC2E9vE9xN5/6+7y8z9A0B1C2D3E4F5G6H7I8J9K0L1M2N3O4P==",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubscriptionId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Username = "podcast_host"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Music.Album", b =>
                {
                    b.HasOne("Domain.Entities.Users.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Domain.Entities.Music.ListeningHistory", b =>
                {
                    b.HasOne("Domain.Entities.Music.Track", "Track")
                        .WithMany("ListeningHistories")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany("ListeningHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Music.Track", b =>
                {
                    b.HasOne("Domain.Entities.Music.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId");

                    b.HasOne("Domain.Entities.Users.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Domain.Entities.Music.TrackGenre", b =>
                {
                    b.HasOne("Domain.Entities.Music.Genre", "Genre")
                        .WithMany("TrackGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Music.Track", "Track")
                        .WithMany("TrackGenres")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Domain.Entities.Playlists.LikedTrack", b =>
                {
                    b.HasOne("Domain.Entities.Music.Track", "Track")
                        .WithMany("LikedByUsers")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany("LikedTracks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Playlists.Playlist", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Playlists.PlaylistTrack", b =>
                {
                    b.HasOne("Domain.Entities.Playlists.Playlist", "Playlist")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Music.Track", "Track")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Domain.Entities.Podcasts.Podcast", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", "Author")
                        .WithMany("Podcasts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Domain.Entities.Podcasts.PodcastEpisode", b =>
                {
                    b.HasOne("Domain.Entities.Podcasts.Podcast", "Podcast")
                        .WithMany("Episodes")
                        .HasForeignKey("PodcastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Podcast");
                });

            modelBuilder.Entity("Domain.Entities.Social.Follower", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", "FollowedUser")
                        .WithMany("Followers")
                        .HasForeignKey("FollowedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users.User", "FollowerUser")
                        .WithMany("Following")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FollowedUser");

                    b.Navigation("FollowerUser");
                });

            modelBuilder.Entity("Domain.Entities.Social.ListeningRoom", b =>
                {
                    b.HasOne("Domain.Entities.Music.Track", "CurrentTrack")
                        .WithMany()
                        .HasForeignKey("CurrentTrackId");

                    b.HasOne("Domain.Entities.Users.User", "Host")
                        .WithMany("HostedRooms")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentTrack");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("Domain.Entities.Social.RoomMember", b =>
                {
                    b.HasOne("Domain.Entities.Social.ListeningRoom", "Room")
                        .WithMany("Members")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany("JoinedRooms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Users.Artist", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithOne("ArtistProfile")
                        .HasForeignKey("Domain.Entities.Users.Artist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Users.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Users.Session", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.HasOne("Domain.Entities.Users.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users.Subscription", "Subscription")
                        .WithMany("Users")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Domain.Entities.Music.Album", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Domain.Entities.Music.Genre", b =>
                {
                    b.Navigation("TrackGenres");
                });

            modelBuilder.Entity("Domain.Entities.Music.Track", b =>
                {
                    b.Navigation("LikedByUsers");

                    b.Navigation("ListeningHistories");

                    b.Navigation("PlaylistTracks");

                    b.Navigation("TrackGenres");
                });

            modelBuilder.Entity("Domain.Entities.Playlists.Playlist", b =>
                {
                    b.Navigation("PlaylistTracks");
                });

            modelBuilder.Entity("Domain.Entities.Podcasts.Podcast", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("Domain.Entities.Social.ListeningRoom", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Domain.Entities.Users.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Domain.Entities.Users.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Users.Subscription", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.Navigation("ArtistProfile");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("HostedRooms");

                    b.Navigation("JoinedRooms");

                    b.Navigation("LikedTracks");

                    b.Navigation("ListeningHistories");

                    b.Navigation("Playlists");

                    b.Navigation("Podcasts");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
