/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common.js";

export interface PremiumSubscriptionInterface extends Interface {
  getFunction(
    nameOrSignature: "buyPremium" | "isPremium" | "owner"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PremiumBought"): EventFragment;

  encodeFunctionData(
    functionFragment: "buyPremium",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPremium",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;

  decodeFunctionResult(functionFragment: "buyPremium", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPremium", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
}

export namespace PremiumBoughtEvent {
  export type InputTuple = [id: BigNumberish, buyer: AddressLike];
  export type OutputTuple = [id: bigint, buyer: string];
  export interface OutputObject {
    id: bigint;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PremiumSubscription extends BaseContract {
  connect(runner?: ContractRunner | null): PremiumSubscription;
  waitForDeployment(): Promise<this>;

  interface: PremiumSubscriptionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyPremium: TypedContractMethod<[_id: BigNumberish], [boolean], "payable">;

  isPremium: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyPremium"
  ): TypedContractMethod<[_id: BigNumberish], [boolean], "payable">;
  getFunction(
    nameOrSignature: "isPremium"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "PremiumBought"
  ): TypedContractEvent<
    PremiumBoughtEvent.InputTuple,
    PremiumBoughtEvent.OutputTuple,
    PremiumBoughtEvent.OutputObject
  >;

  filters: {
    "PremiumBought(int256,address)": TypedContractEvent<
      PremiumBoughtEvent.InputTuple,
      PremiumBoughtEvent.OutputTuple,
      PremiumBoughtEvent.OutputObject
    >;
    PremiumBought: TypedContractEvent<
      PremiumBoughtEvent.InputTuple,
      PremiumBoughtEvent.OutputTuple,
      PremiumBoughtEvent.OutputObject
    >;
  };
}
